kwiz/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from .views import (ApplicationView, CreateEventView, CreatePostView, EventDetailView, MainView, PostDetailView, 
                    PostsListView, create_feedback, delete_event, delete_feedback, delete_post, edit_event, edit_post, 
                    login_view, register_view, user_profile, logout_view, user_profile_event,
                    subscribe_view, edit_event_status, admin_profile_event)

urlpatterns = [
    path('', MainView.as_view(), name='main'),
    path('login/' , login_view, name='login'),
    path('register/', register_view, name='register'),
    path('logout/', logout_view, name='logout'),
    path('profile/', user_profile, name='profile'),
    path('profile/event/', user_profile_event, name='profile_event'),
    path('profile/event/admin', admin_profile_event, name='profile_event_admin'),

    path('create_event', CreateEventView.as_view(), name='create_event'),
    path("event/<int:pk>/", EventDetailView.as_view(), name="detail_event"),
    path("event/edit/<int:pk>/", edit_event, name="edit_event"),
    path("event/edit/status/", edit_event_status, name="edit_event_status"),
    path('event/<int:pk>/<str:slug>', ApplicationView.as_view(), name='applications'),
    path("event/apply/<int:pk>/", subscribe_view, name="subscribe"),
    path("event/delete/", delete_event, name="delete_event"),

    path('posts/', PostsListView.as_view(), name='posts'),
    path('create_post/', CreatePostView.as_view(), name='create_post'),
    path("post/<int:pk>/", PostDetailView.as_view(), name="detail_post"),
    path("post/edit/", edit_post, name="edit_post"),
    path("post/delete/", delete_post, name="delete_post"),

    path('feedback/create/', create_feedback, name='create_feedback'),
    path('feedback/delete/', delete_feedback, name='delete_feedback'),

]

main/models.py
from django.contrib.auth.models import AbstractUser

from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils import timezone





EventType_Choices = (
    ("Интеллектуальный квиз", "Интеллектуальный квиз"),
    ("Музыкальный квиз", "Музыкальный квиз"),
    ("Спортивное мероприятие", "Спортивное мероприятие"),
    ("Классическая Мафия", "Классическая Мафия"),
    ("Своя Игра", "Своя Игра"),
    ("Интеллектуальная игра 100к1", "Интеллектуальная игра 100к1"),
    ("Брейн-ринг", "Брейн-ринг")
)

EducationLevel_Choices = (
    ("Младшее звено 1-4 классы", "Младшее звено 1-4 класс"),
    ("Среднее звено 5-7 классы", "Среднее звено 5-7 классы"),
    ("Старшее звено 8-11 классы", "Старшее звено 8-11 классы")
)

klass_Choices = (
    ('5А','5А'),
    ('5Б','5Б'),
    ('5В','5В'),
    ('5Г','5Г'),
    ('6А','6А'),
    ('6Б','6Б'),
    ('6В','6В'),
    ('6Г','6Г'),
    ('7А','7А'),
    ('7Б','7Б'),
    ('7В','7В'),
    ('7Г','7Г'),
    ('8А','8А'),
    ('8Б','8Б'),
    ('8В','8В'),
    ('8Г','8Г'),
    ('9А','9А'),
    ('9Б','9Б'),
    ('9В','9В'),
    ('9Г','9Г'),
    ('10А','10А'),
    ('10Б','10Б'),
    ('10В','10В'),
    ('10Г','10Г'),
    ('11А','11А'),
    ('11Б','11Б'),
    ('11В','11В'),
    ('11Г','11Г'),
)

Status_Choices = (
    ("На рассмотрении", "На рассмотрении"),
    ("Принята", "Принята"),
    ("Отклонена", "Отклонена"),
    ("Отменена", "Отменена"),
    ("Посещено", "Посещено")
)


class CustomUser(AbstractUser):
    class_scool = models.CharField(max_length=10, choices=klass_Choices)

    def __str__(self) -> str:
        return f"{self.username} {self.last_name}, {self.class_scool}"


class EventType(models.Model):
    name = models.CharField(max_length=100,
                            verbose_name='Наименование типа мероприятия',
                            choices=EventType_Choices)

    def __str__(self):
        return f"{self.name}"


class EducationLevel(models.Model):
    name = models.CharField(max_length=100,
                            verbose_name='Наименование степени обучающихся (звена)',
                            choices=EducationLevel_Choices)

    def __str__(self):
        return f"{self.name}"


class Event(models.Model):
    title = models.CharField(max_length=255, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    max_eventers = models.IntegerField(default=100)
    location = models.CharField(max_length=255, null=True, blank=True)
    date_event = models.DateTimeField(null=True, blank=True)
    event_type = models.ForeignKey('EventType', on_delete=models.CASCADE)
    education_level = models.ForeignKey('EducationLevel', on_delete=models.CASCADE)
    responsible = models.ForeignKey('CustomUser', null=True, blank=True, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='images', null=True, blank=True)
    
    def __str__(self):
        return str(self.title)
    
    def get_absolute_url(self):
        return reverse("detail_event", kwargs={"pk": self.pk})
    
    

class Application(models.Model):
    date_submitted = models.DateField(blank=True, null=True, default=timezone.now)
    event = models.ForeignKey('Event', blank=True, null=True, on_delete=models.CASCADE)
    user = models.ForeignKey('CustomUser', on_delete=models.CASCADE, null=True, blank=True)
    status = models.ForeignKey('Status', on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return f"{self.user}, {self.date_submitted}"


class Results(models.Model):
    event = models.ForeignKey('Event', null=True, blank=True, on_delete=models.CASCADE)
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return str(self.description)


class Post(models.Model):
    title = models.CharField(max_length=255, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    image = models.ImageField(upload_to='images', null=True, blank=True)
    user = models.ForeignKey('CustomUser', blank=True, null=True, on_delete=models.CASCADE)
    time_submit = models.DateTimeField(null=True, blank=True, default=timezone.now)

    def __str__(self):
        return f"{self.title} | {self.user}"

    def get_absolute_url(self):
        return reverse('post_detail', args=(str(self.pk)))


class Feedback(models.Model):
    feedback = models.TextField(null=True, blank=True)
    time_submit = models.DateTimeField(null=True, blank=True, default=timezone.now)
    user = models.ForeignKey('CustomUser', blank=True, null=True, on_delete=models.CASCADE)
    event = models.ForeignKey('Event', blank=True, null=True, on_delete=models.CASCADE)
    post = models.ForeignKey('Post', blank=True, null=True, on_delete=models.CASCADE)
    
    def __str__(self):
        return str(self.feedback)

class Status(models.Model):
    title = models.CharField(max_length=255, verbose_name='Статус заявки', choices=Status_Choices, blank=True)

    def __str__(self):
        return str(self.title)

main/views.py
from datetime import datetime
from typing import Any
from django.contrib import messages
from django.db.models.query import QuerySet
from django.contrib.auth import authenticate, login, logout
from django.http import HttpRequest, HttpResponse
from django.shortcuts import redirect, render
from django.views.generic.edit import FormView, FormMixin
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from .models import *
import datetime


# from main.models import CustomUser

from .forms import ChangePasswordForm, CommentForm, CreateEventForm, CreatePostForm, EditContactDataForm, FeedbackCreateForm, FeedbackForm, LoginForm, RegisterForm
# user = CustomUser()


def login_view(request):
    if request.method == 'GET':
        if request.user.is_active:
            return redirect('/')
    if request.method == 'POST':
        login_form = LoginForm(request.POST)
        if login_form.is_valid():
            name = login_form.cleaned_data.get('name')
            password = login_form.cleaned_data.get('password')
            user = authenticate(request,    username=name, password=password)
            if user is not None:
                login(request, user)
                return redirect('main')
            else:
                return render(request, 'login.html', {'login_form': login_form, 'error': 'Неверный логин или пароль'})
    login_form = LoginForm()
    return render(request, 'login.html', {'login_form': login_form})

def register_view(request):
    register_form = RegisterForm(request.POST)
    if request.method == 'GET':
        if request.user.is_active:
            return redirect('/')
    if request.method == 'POST':
        if register_form.is_valid():
            user = CustomUser()
            user.username = register_form.cleaned_data.get('name')
            user.last_name = register_form.cleaned_data.get('surname')
            user.school_class = register_form.cleaned_data.get('school_class')
            user.set_password(register_form.cleaned_data.get('password'))
            user.save()  # Сохраняем пользователя
            return redirect('main')
    else:
        register_form = RegisterForm()
    return render(request, 'register.html', {'register_form': register_form})

def user_profile(request):
    """ Обрабатывает в личном кабинете две формы на изменение контактных данных и пароля пользователя """
    user = request.user
    edit_contact_data_form = EditContactDataForm(instance=user)
    change_pass_form = ChangePasswordForm()
    context = {'edit_contact_data_form': edit_contact_data_form,
            'change_pass_form': change_pass_form, }
    context['active'] =  {'profile': 'active'}
    if request.method == "POST":
        # Изменяем контактные данные пользователя
        if 'edit_contact_data' in request.POST:
            edit_contact_data_form = EditContactDataForm(request.POST, instance=user)
            if edit_contact_data_form.is_valid():
                edit_contact_data_form.save()
                messages.success(request, "Контактные данные пользователя успешно изменены!")
                return redirect('profile')
        # Изменяем пароль пользователя
        elif 'change_password' in request.POST:
            change_pass_form = ChangePasswordForm(request.POST, instance=user)
            if change_pass_form.is_valid():
                password = change_pass_form.cleaned_data.get("password")
                new_password = change_pass_form.cleaned_data.get("new_password")
                repeat_new_pass = change_pass_form.cleaned_data.get("repeat_new_pass")
                if user.check_password(password) and new_password == repeat_new_pass:
                    user.set_password(new_password)
                    user.save()
                    messages.success(request, "Пароль пользователя успешно изменён!")
                    return redirect('profile')
        context = {'edit_contact_data_form': edit_contact_data_form,
            'change_pass_form': change_pass_form, }  
    return render(request, 'profile.html', context=context)


def logout_view(request):
    logout(request)
    return redirect('main')


def user_profile_event(request):
    aplication = Application.objects.filter(user_id=request.user.id).select_related('event').select_related('status')
    context = {'aplication': aplication}
    return render(request, 'profile_list_event.html', context=context)


def admin_profile_event(request):
    event = Event.objects.all()
    context = {'event': event}
    return render(request, 'profile_list_event_admin.html', context=context)


    pass

def edit_event_status(request):
     if request.method == 'POST':
        event_id = request.POST.get('event_id')
        status = Status.objects.get(id=4)# Отменена
        aplication = Application.objects.filter(event=event_id).select_related('status').update(status=status)
        return redirect(request.META.get('HTTP_REFERER'))



def subscribe_view(request, pk):
    now = datetime.datetime.now()
    status = Status.objects.get(id=1) 

    if request.method == 'GET':
        aplication, created = Application.objects.get_or_create(
            user_id=request.user.id,
            event_id=pk,
            defaults={'date_submitted': now, 'status': status})
        
    return redirect(request.META.get('HTTP_REFERER'))

    

class MainView(ListView):
    model = Event
    paginate_by = 20
    template_name = 'index.html'
    ordering = ['-id']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['active'] =  {'event': 'active'}
        context['user_is_staff'] = self.request.user.is_staff
        return context

    def get(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse:
        
        return super().get(request, *args, **kwargs)
    

class CreateEventView(FormView):
    template_name = 'create_event.html'
    form_class = CreateEventForm
    success_url = '/create_event/'

    def post(self, request: HttpRequest, *args: str, **kwargs: Any) -> HttpResponse:
        event = CreateEventForm(request.POST, request.FILES)
        if event.is_valid():
            event.save()
            return redirect('/')
        return super().post(request, *args, **kwargs)
    

class EventDetailView(DetailView):
    model = Event
    form_class = CreateEventForm
    template_name = 'event_detail.html'

    def get_context_data(self, **kwargs):
        # self.request.session['error_message'] = '' 
        context = super().get_context_data(**kwargs)
        context["form"] = CreateEventForm(context['event'].__dict__)
        context["feedback_form"] = FeedbackForm()
        context["feedback_list"] = Feedback.objects.select_related('event').filter(event_id=context['event'].id).order_by('-time_submit')
        context['user_is_staff'] = self.request.user.is_staff
        return context


def edit_event(request, pk):
    one_rec = Event.objects.get(id=pk)
    form = CreateEventForm(instance=one_rec)
    if request.method == 'POST':
        form = CreateEventForm(request.POST, instance=one_rec)  # Обновляем форму с данными из POST-запроса
        if form.is_valid():  # Проверяем валидность формы
            form.save()  # Сохраняем обновленные данные в базе данных
        return redirect(request.META.get('HTTP_REFERER'))
    mydict= {'form':form}
    return render(request,'edit_event.html',context=mydict)


def delete_event(request):
    if request.method == 'POST':
        one_rec = Event.objects.get(id=request.POST.get('event'))
        if one_rec:
            one_rec.delete()
        return redirect('/')
    return redirect(request.META.get('HTTP_REFERER'))


class PostsListView(ListView):
    model = Post
    paginate_by = 20
    template_name = 'posts.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['active'] =  {'post': 'active'}
        context['user_is_staff'] = self.request.user.is_staff
        return context

    def get(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse:
        
        return super().get(request, *args, **kwargs)
    

class CreatePostView(FormView):
    template_name = 'create_post.html'
    form_class = CreatePostForm
    success_url = '/create_post/'

    def post(self, request: HttpRequest, *args: str, **kwargs: Any) -> HttpResponse:
        event = CreatePostForm(request.POST, request.FILES)
        if event.is_valid():
            event.save()
            return redirect('posts')
        return super().post(request, *args, **kwargs)


class PostDetailView(DetailView):
    model = Post
    form_class = CreatePostForm
    template_name = 'post_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["feedback_list"] = Feedback.objects.select_related('post').filter(post_id=context['post'].id).order_by('-time_submit')
        context["feedback_form"] = CommentForm()
        
        if self.request.GET.get('mode'):
            if self.request.GET.get('mode') == 'edit':
                context["edit"] = True
                inc = Post.objects.get(id=self.kwargs.get('pk'))
                context["form"] = CreatePostForm(instance=inc)
                context["img"] = inc.image
        return context
    

def create_feedback(request):
    if request.method == 'POST':
        form = FeedbackCreateForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            form.save()
            return redirect(request.META.get('HTTP_REFERER'))
        mydict={'feedback_form': form}
        return redirect(request.META.get('HTTP_REFERER'), context=mydict)
    else:
        return redirect(request.META.get('HTTP_REFERER'))
    
def delete_feedback(request):
    if request.method == 'POST':
        one_rec = Feedback.objects.get(pk=request.POST.get('feedback'))
        if one_rec:
            one_rec.delete()

main/templates/application.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    <title>{{ title }}</title>
{% endblock %}

{% block stylesheet %}{% endblock %}

{% block content %}
{% if user.is_staff %}

<div class="mb-2 d-flex justify-content-between">
    {% if apply %}
    <a href="{% url 'applications' event.id 'visit_log' %}" class="btn btn-warning">Журнал</a>
    {% elif visit_log %}
    <a href="{% url 'applications' event.id 'apply' %}" class="btn btn-success">Заявки</a>
    {% endif %}
    <div class="fs-5 col-9">{{event.title}}</div>
</div>
{% endif %}
<div class="card">
    <div class="card-header">
        Список заявок
    </div>
    <div class="card-body">
        <ul class="list-group">
            {% for object in object_list %}
            <li class="row">
                <div class="col d-flex justify-content-between">
                    <div>{{ object.user }}</div>
                    <div class="btn-group">
                        {% if apply %}
                        <form action="{% url 'change_status_application' %}" method="post">
                            {% csrf_token %}
                            <input type="hidden" readonly name="apply_id" value="{{ object.id }}">
                            <input type="hidden" readonly name="status_id" value="2">
                            <input type="submit" class="btn btn-success" value="Принять">
                        </form>
                        <form action="{% url 'change_status_application' %}" method="post">
                            {% csrf_token %}
                            <input type="hidden" readonly name="apply_id" value="{{ object.id }}">
                            <input type="hidden" readonly name="status_id" value="3">
                            <input type="submit" class="btn btn-warning" value="Отклонить">
                        </form>
                        {% elif visit_log %}
                        <form action="{% url 'change_status_application' %}" method="post">
                            {% csrf_token %}
                            <input type="hidden" readonly name="apply_id" value="{{ object.id }}">
                            <input type="hidden" readonly name="status_id" value="5">
                            {% if object.status_id == 2 %}
                            <input type="submit" class="btn btn-warning" value="Подтвердить">
                            {% elif object.status_id == 5 %}
                            <input type="submit" class="btn btn-primary" value="Участвовал" disabled>
                            {% endif %}
                        </form>
                        {% endif %}
                    </div>
                </div>
            </li>
            <hr/>
            {% empty %}
            <li>Список мероприятий пуст.</li>
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}

main/templates/create_event.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    <title>Создание мероприятия</title>
{% endblock %}

{% block stylesheet %}{% endblock %}

{% block content %}
<div class="card">
    <div class="card-header">
        Регистрация нового мероприятия
    </div>
    <div class="card-body">
        <form action="" method="post" class="create__form d-flex flex-column w-full" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
            <button type="submit" class="btn btn-primary mt-2">Создать</button>
        </form>
    </div>
</div>
{% endblock %}

main/templates/event_detail.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    <title>{{ object.title }}</title>
{% endblock %}

{% block stylesheet %}{% endblock %}

{% block content %}
<div class="nav mb-2 d-flex justify-content-between">
    {% if user.is_staff %}
    <div class="btn-group">
        <a href="{% url 'applications' object.id 'apply' %}" class="btn btn-success">Заявки</a>
        <a href="{% url 'applications' object.id 'visit_log' %}" class="btn btn-warning">Журнал</a>
    </div>
    <form action="{% url 'delete_event' %}" method="post">
        {% csrf_token %}
        <input type="hidden" readonly name="event" value="{{ event.id }}">
        <input type="submit" class="btn btn-danger" value="Удалить">
    </form>
    {% else %}
    <a href="{% url 'apply' %}" class="btn btn-primary">Подать заявку</a>
    {% endif %}
</div>
<div class="card">
    <div class="card-header">
        О мероприятии
    </div>
    <div class="card-body">
        <form action="" method="post" class="create__form d-flex flex-column w-full" enctype="multipart/form-data">
            {% csrf_token %}
            {{ object }}
            {% if user_is_staff %}
            <a class="btn btn-primary ms-auto" aria-current="page" href="{% url 'edit_event' object.pk %}">Редактировать событие</a>
            {% else %}
            {% if user.is_authenticated %}
            <a class="btn btn-primary ms-auto" aria-current="page"  href="{% url 'subscribe' object.pk %}" class="nav-link">Подать заявку</a>
            {% comment %} <button type="submit" class="btn btn-primary">Подать заявку</button> {% endcomment %}
            {% else %}
            <a class="btn btn-primary ms-auto" aria-current="page"  href="{% url 'login' %}" class="nav-link">Подать заявку</a>
            {% endif %}
            {% endif %}
        </form>
    </div>
</div>
<div class="card mt-3">
    <div class="card-body">
        <form action="{% url 'create_feedback' %}" method="post" class="create__form d-flex flex-column w-full" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="hidden" readonly name="user" id="id_usert" value="{{ user.id }}">
            <input type="hidden" readonly name="event" id="id_event" value="{{ event.id }}">
            {{ feedback_form }}
            <button type="submit" class="btn btn-primary mt-2">Отправить</button>
        </form>
    </div>
</div>
<div class="card mt-3">
    <div class="card-header">
        Отзывы
    </div>
    <div class="card-body">
        <ul class="list-group">
            {% for object in feedback_list %}
            <li class="row d-flex flex-column w-full">
                <div class="col-12 mb-4">{{ object.feedback }}</div>
                <div class="col-12 d-flex justify-content-between">
                    <div class="col-9 d-flex flex-column">
                        <p class="mb-2 text-end text-muted fs-6">{{ object.user }}</p>
                        <span class="text-end text-muted fs-6">{{ object.time_submit }}</span>
                    </div>
                    {% if user.is_staff %}
                    <div class="col-2">
                        <form action="{% url 'delete_feedback' %}" method="post">
                            {% csrf_token %}
                            <input type="hidden" readonly name="feedback" value="{{ object.id }}">
                            <button class="btn btn-danger ms-auto" type="submit">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash3" viewBox="0 0 16 16">
                                    <path d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5M11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47M8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5"/>
                                </svg>
                            </button>
                        </form>
                    </div>
                    {% endif %} 
                </div>
            </li>
            <hr/>
            {% empty %}
            <li>Отзывов нет.</li>
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}

main/templates/post_detail.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    <title>{{ post.title }}</title>
{% endblock %}

{% block stylesheet %}{% endblock %}

{% block content %}
{% if edit %}
<a href="{% url 'detail_post' post.id %}" class="btn btn-primary mb-3">⬅️Назад</a>
<div class="card">
    <div class="card-body">
        <form action="{% url 'edit_post' %}" method="post" class="d-flex flex-column">
            {% csrf_token %}
            <input type="hidden" readonly name="post" value="{{post.id}}">
            {{form}}
            <input type="submit" class="btn btn-success mt-2" value="Изменить">
        </form>
        <div class="actual_photo mt-3 mb-2">Актуальное фото</div>
        <img src="/{{img}}" alt="photo">
    </div>
</div>
{% else %}
{% if user.is_staff %}
    <div class="nav mb-2 d-flex justify-content-between">
        <a href="{% url 'detail_post' post.id %}?mode=edit" class="btn btn-success">Изменить</a>
        <form action="{% url 'delete_post' %}" method="post">
            {% csrf_token %}
            <input type="hidden" readonly name="post" value="{{ post.id }}">
            <input type="submit" class="btn btn-danger" value="Удалить">
        </form>
    </div>
{% endif %}
<div class="card">
    <div class="card-body">
        <div class="">{{ post.title }}</div>
        <div class="">
            <img src="/{{ post.image }}" alt="photo">
        </div>
        <div class="">{{ post.description }}</div>
    </div>
</div>
<div class="card mt-3">
    <div class="card-body">
        <form action="{% url 'create_feedback' %}" method="post" class="create__form d-flex flex-column w-full" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="hidden" readonly name="user" id="id_user" value="{{ user.id }}">
            <input type="hidden" readonly name="post" id="id_post" value="{{ post.id }}">
            {{ feedback_form }}
            <button type="submit" class="btn btn-primary mt-2">Отправить</button>
        </form>
    </div>
</div>
<div class="card mt-3">
    <div class="card-header">
        Комментарии
    </div>
    <div class="card-body">
        <ul class="list-group">
            {% for object in feedback_list %}
            <li class="row d-flex flex-column w-full">
                <div class="col-12 mb-4">{{ object.feedback }}</div>
                <div class="col-12 d-flex justify-content-between">
                    <div class="col-9 d-flex flex-column">
                        <p class="mb-2 text-end text-muted fs-6">{{ object.user }}</p>
                        <span class="text-end text-muted fs-6">{{ object.time_submit }}</span>
                    </div> 
                    {% if user.is_staff %}
                    <div class="col-2">
                        <a class="btn btn-danger ms-auto" aria-current="page" href="{% url 'delete_feedback' object.id %}">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash3" viewBox="0 0 16 16">
                                <path d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5M11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47M8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5"/>
                            </svg>
                        </a>
                    </div>
                    {% endif %} 
                </div>
            </li>
            <hr/>
            {% empty %}
            <li>Комментариев нет.</li>
            {% endfor %}
        </ul>
    </div>
</div>
{% endif %}
{% endblock %}